on:
  workflow_dispatch:

name: Run benchmarks
jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    - name: Set up JDK
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: temurin
        java-version: 17

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5
      with:
        gradle-home-cache-cleanup: true
        cache-read-only: true
        add-job-summary: always
        validate-wrappers: true

    - name: Run benchmarks
      shell: bash
      run: ./gradlew :benchmark:benchmark -PenableNativeTargets --stacktrace
