on:
  push:
    branches:
      - develop
      - renovate/**
  pull_request:
    branches:
      - develop

name: Run tests
jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    - name: Set up JDK
      uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
      with:
        distribution: temurin
        java-version: 18
        cache: gradle

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812 # v3.2.5
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'settings.gradle.kts') }}

    - name: Run unit tests
      uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
      with:
        arguments: check -PenableNativeTargets --stacktrace
