on:
  push:
    branches:
      - develop
      - renovate/**
  pull_request:
    branches:
      - develop

name: Run tests
jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-11
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.0.2

    - name: Set up JDK
      uses: actions/setup-java@v3.4.1
      with:
        distribution: temurin
        java-version: 18
        cache: gradle

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@v3.0.5
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'settings.gradle.kts') }}

    - name: Run unit tests
      uses: gradle/gradle-build-action@v2.2.2
      with:
        arguments: check --stacktrace
