on:
  push:
    tags:
      - v*

name: Release to Maven Central
jobs:
  create_staging_repository:
    runs-on: ubuntu-latest
    name: Create staging repository
    outputs:
      repository_id: ${{ steps.create.outputs.repository_id }}
    steps:
      - id: create
        uses: nexus-actions/create-nexus-staging-repo@3e5e7209801629febdcf75541a4898710d28df9a # v1.2
        with:
          username: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
          password: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
          staging_profile_id: ${{ secrets.NEXUS_PUBLISH_STAGING_PROFILE_ID }}
          description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}

  publish:
    runs-on: macos-11
    needs: create_staging_repository
    steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up JDK
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 18
        cache: gradle

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'settings.gradle.kts') }}

    - name: Publish
      uses: gradle/gradle-build-action@40b6781dcdec2762ad36556682ac74e31030cfe2 # v2.5.1
      with:
        arguments: publishAllPublicationsToSonatypeRepository -PenableNativeTargets
      env:
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.NEXUS_PUBLISH_GPG_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.NEXUS_PUBLISH_GPG_KEY_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
        SONATYPE_REPOSITORY_ID: ${{ needs.create_staging_repository.outputs.repository_id }}

  publish_windows:
    runs-on: windows-latest
    needs: create_staging_repository
    steps:
    - name: Checkout repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up JDK
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: 18
        cache: gradle

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'settings.gradle.kts') }}

    - name: Publish Windows artifacts
      uses: gradle/gradle-build-action@40b6781dcdec2762ad36556682ac74e31030cfe2 # v2.5.1
      with:
        arguments: publishMingwX64PublicationToSonatypeRepository publishMingwX86PublicationToSonatypeRepository -PenableNativeTargets
      env:
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.NEXUS_PUBLISH_GPG_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.NEXUS_PUBLISH_GPG_KEY_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
        SONATYPE_REPOSITORY_ID: ${{ needs.create_staging_repository.outputs.repository_id }}

  finalize:
    runs-on: ubuntu-latest
    needs: [create_staging_repository, publish, publish_windows]
    if: ${{ always() && needs.create_staging_repository.result == 'success' }}
    steps:
      - name: Discard
        if: ${{ needs.publish.result != 'success' || needs.publish_windows.result != 'success' }}
        uses: nexus-actions/drop-nexus-staging-repo@fe83783967a063540320ace3c8942608246705a1 # v1
        with:
          username: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
          password: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
          staging_repository_id: ${{ needs.create_staging_repository.outputs.repository_id }}
      - name: Release
        if: ${{ needs.publish.result == 'success' && needs.publish_windows.result == 'success' }}
        uses: nexus-actions/release-nexus-staging-repo@36161f25ef98cc3821eabb11ab742d2e9d479e52 # v1.2
        with:
          username: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
          password: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
          staging_repository_id: ${{ needs.create_staging_repository.outputs.repository_id }}
