on:
  push:
    tags:
      - v*

name: Release to Maven Central
jobs:
  create_staging_repository:
    runs-on: ubuntu-latest
    name: Create staging repository
    outputs:
      repository_id: ${{ steps.create.outputs.repository_id }}
    steps:
      - id: create
        uses: nexus-actions/create-nexus-staging-repo@3e5e7209801629febdcf75541a4898710d28df9a # v1.2
        with:
          username: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
          password: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
          staging_profile_id: ${{ secrets.NEXUS_PUBLISH_STAGING_PROFILE_ID }}
          description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}

  publish:
    runs-on: macos-latest
    needs: create_staging_repository
    steps:
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Set up JDK
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        distribution: temurin
        java-version: 11

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
      with:
        gradle-home-cache-cleanup: true
        cache-read-only: true
        add-job-summary: always
        validate-wrappers: true

    - name: Publish
      shell: bash
      run: ./gradlew publishAllPublicationsToSonatypeRepository -PenableNativeTargets
      env:
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.NEXUS_PUBLISH_GPG_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.NEXUS_PUBLISH_GPG_KEY_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
        SONATYPE_REPOSITORY_ID: ${{ needs.create_staging_repository.outputs.repository_id }}

  publish_windows:
    runs-on: windows-latest
    needs: create_staging_repository
    steps:
    - name: Checkout repository
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

    - name: Set up JDK
      uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
      with:
        distribution: temurin
        java-version: 11

    - name: Cache Kotlin/Native compiler
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ~/.konan
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
      with:
        gradle-home-cache-cleanup: true
        cache-read-only: true
        add-job-summary: always
        validate-wrappers: true

    - name: Publish Windows artifacts
      shell: bash
      run: ./gradlew publishMingwX64PublicationToSonatypeRepository -PenableNativeTargets
      env:
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.NEXUS_PUBLISH_GPG_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.NEXUS_PUBLISH_GPG_KEY_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
        SONATYPE_REPOSITORY_ID: ${{ needs.create_staging_repository.outputs.repository_id }}

  finalize:
    runs-on: ubuntu-latest
    needs: [create_staging_repository, publish, publish_windows]
    if: ${{ always() && needs.create_staging_repository.result == 'success' }}
    steps:
      - name: Discard
        if: ${{ needs.publish.result != 'success' || needs.publish_windows.result != 'success' }}
        uses: nexus-actions/drop-nexus-staging-repo@fe83783967a063540320ace3c8942608246705a1 # v1
        with:
          username: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
          password: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
          staging_repository_id: ${{ needs.create_staging_repository.outputs.repository_id }}

      - name: Release
        if: ${{ needs.publish.result == 'success' && needs.publish_windows.result == 'success' }}
        uses: nexus-actions/release-nexus-staging-repo@36161f25ef98cc3821eabb11ab742d2e9d479e52 # v1.2
        with:
          username: ${{ secrets.NEXUS_PUBLISH_USERNAME }}
          password: ${{ secrets.NEXUS_PUBLISH_PASSWORD }}
          staging_repository_id: ${{ needs.create_staging_repository.outputs.repository_id }}
