/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.sphericalkat

import dev.sphericalkat.sublimefuzzy.Fuzzy
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = Fuzzy()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
